### ISSUE TITLE
.NET example

### ISSUE THREAD

**Issue by egimisis** [entersoftsa/eswebapi#1]
Is there a .NET example available, calling the web api using C# or VB.NET ?
Especially, is there such an example, demonstrating the use of fiImportDocument(xmldocstr) function ?

Thanks in advance
For Synectics SA

E. Gimissis
MSc ICSD
MCP

**Comment by entersoftsa** [comment]
Hi there,
There is an extensive article in Entersoft's Knowledge Base on how to use FIImportDocs within a programming environment (there are no significant changes whether you call this function from the .NET code or from WEB API).
Please visit: 
http://www.entersoft.gr/KBArticle/Διαδικασία%20εισαγωγής%20παραστατικών%20από%20XML/MEMBERS_slh_KnowledgeBase

Should you have more questions and you are a certified Entersoft Consultant you may address support@entersoft.eu

Thanks

**Comment by Intertranslations** [comment]
Unfortunately after all these yoear link is dead. May I have its current residence address ?
