### ISSUE TITLE
webapi documentation

### ISSUE THREAD

**Issue by navitatis** [entersoftsa/eswebapi#2]
Looking for documentation or examples on making calls directly to the web api, not through the provided angualjs api. 

Specifically, I use php and curl. I can successfully create a session and make a call to fetchPublicQuery() but I get the following response:

`{
  "MessageID": "",
  "UserMessage": "",
  "Messages": [
    "Δεν έχει σημειωθεί ότι ο τύπος 'Newtonsoft.Json.Linq.JArray' στη συγκρότηση 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' έχει δυνατότητα σειριοποίησης.",
    "System.Collections.Hashtable",
    "Serialize and Compress object Hashtable was failed",
    "System.Collections.Hashtable",
    "Serialize and Compress object Hashtable was failed"
  ]
}`

Thanks in advance,
Spiros Gatzounas

**Comment by BabisAvratoglou** [comment]
For Entersoft WEB API, what the calling environment is, is irrelevant. Either curl or angular , javascript , jquery, php, .net  or whatever will do, provided that the GET or POST command sent to the server is formed correctly.
For example the fetch publicquery API has certain requirements for its parameters depending on the  GET or POST commands as you may see in the respective source code in :

Eswebapi/src/js/eswebservice.js

So, either the EBS Application server version is incorrect (pls use version 4.0.42.0 or more recent)  or there is an error in the parameters passed for the PublicQuery API, which leads deserialization in the Web API Server to fail.

fetchPublicQuery: function(pqGroupID, pqFilterID, pqOptions, pqParams, httpVerb) {
                                var group;
                                var execParams;
                                if (pqGroupID instanceof esGlobals.ESPublicQueryDef) {
                                    group = (pqGroupID.GroupID || "").trim();
                                    pqFilterID = (pqGroupID.FilterID || "").trim();
                                    pqOptions = pqGroupID.PQOptions;
                                    execParams = pqGroupID.Params;
                                } else {
                                    group = pqGroupID ? pqGroupID.trim() : "";
                                    pqFilterID = pqFilterID ? pqFilterID.trim() : "";
                                    execParams = pqParams;
                                }

                                if (execParams && execParams instanceof esGlobals.ESParamValues) {
                                    execParams = execParams.getExecuteVals();
                                }

                                var surl = urlWEBAPI.concat(ESWEBAPI_URL.__PUBLICQUERY__, group, "/", pqFilterID);
                                var tt = esGlobals.trackTimer("PQ", "FETCH", group.concat("/", pqFilterID));
                                tt.startTime();

                                /**
                                 * $http object configuration
                                 * @type {Object}
                                 */
                                var httpConfig = {
                                    headers: prepareHeaders(),
                                    url: surl,
                                    params: execParams
                                };

                                if (pqOptions) {
                                    httpConfig.headers["X-ESPQOptions"] = JSON.stringify(pqOptions);
                                }

                                //if called with 3 arguments then default to a GET request
                                httpConfig.method = httpVerb || 'GET';

                                //if not a GET request, switch to data instead of params
                                if (httpConfig.method !== 'GET') {
                                    delete httpConfig.params;
                                    httpConfig.data = execParams;
                                }

                                var ht = $http(httpConfig);
                                return processWEBAPIPromise(ht, tt);
                            },


You may find a pure JS example here:
[NewUpdateCustomerFromScrollerAutomation.zip](https://github.com/entersoftsa/eswebapi/files/755034/NewUpdateCustomerFromScrollerAutomation.zip)

**Comment by smene** [comment]
Please look at Babis response. Entersoft WEB API Server is not bound to any specific programming environment. You can access it through any client that can perform http and https GET / POST calls and supports application/json content type in request and response messages.

**Comment by ChrisInv** [comment]
Hello,

we would need some language-agnostic API documentation for the Entersoft WEB API Server. What endpoints/methods are available, what parameters they expect, what they return, and so on. Is there such documentation available?

Also, we are looking for some clear instructions on what needs to be installed, and how exactly, in order to enable the Web API functionality for our Entersoft installation. Is it possible to install the API on a proxy machine, different than the one Entersoft is installed on, so as to not directly expose the Entersoft installation to the internet?

Could you please point us to the right direction.

Thank you in advance,
Chris

**Comment by BabisAvratoglou** [comment]
Hi you may find the API reference in http://developer.entersoft.gr/eswebapi/#/api/es.Services.Web.esWebApi
on the top of his page there is a button leading to the Installation instructions page.
The WEB API server may be installed anywhere provided that is has access (through an IP:port) to an EBS application server. 
I
