### ISSUE TITLE
fiImportDocument(xmldocstr)

### ISSUE THREAD

**Issue by Softweb-Adaptive-IT-Solutions** [entersoftsa/eswebapi#4]
Καλησπέρα, ενδιαφέρομαι να χρησιμοποιήσω αυτήν την μέθοδο του API για να εισάγω παραστατικά  παραγγελίας. Μήπως υπάρχει κάτι πιο κατάλληλο απο την fiImportDocument ? Σαν params λέει να δημιουργήσουμε ένα xmldocstr. Μπορώ να βρω κάπου πως να σχηματίσω αυτό το xml.

**Comment by entersoftsa** [comment]
Καλησπέρα,

Όπως πολύ συχνά συμβαίνει, για μία ανάγκη υπάρχουν ενδεχομένως περισσότερες της μία λύσης, ανάλογα με τον ορισμό του ζητούμενου. Εν προκειμένω παρ/κό μπορείτε να εισάγετε:


  1.  Μέσω της fiImportDocument όπου για την σχετική τεκμηρίωση θα πρέπει να απευθυνθείτε στο support@entersoft.gr<mailto:support@entersoft.gr> ή και στη Βάση Γνώσης http://kb.entersoft.gr
  2.  Μέσω αυτοματισμών (ανάλογα το τι παρ/κό και γραμμές )

Με εκτίμηση,

Stavros Menegos

**Comment by selini** [comment]
Ευχαριστώ για την απάντηση. Απευθύνθηκα στο support και μου έδωσαν όλα όσο χρειαζόμουν. Έχω ένα πρόβλημα το call όμως.

Αυτό είναι το xml που σχημάτισα. Λειτουργεί αν το βάλω σαν αρχείο απευθείας στο server, κάνει εισαγωγή κανονικά.

<?xml version='1.0' encoding='UTF-8'?>
<TradeDocumentDS>

```
<ESFIDocumentTrade>
<version>1</version>
<fADDocumentTypeGID>ΠΑΡ</fADDocumentTypeGID>
<fADDocumentSeriesGID>ΚΕΝ-Α</fADDocumentSeriesGID>
<AdStringfield1>INTERNET</AdStringfield1>
<fTradeAccountGID>ce0052bb-cd7b-4918-a900-8b5cb04528c7</fTradeAccountGID>
<fdeliverysiteGID>1</fdeliverysiteGID></ESFIDocumentTrade>

<ESFILineItem>
<LineType>6</LineType>
<fitemGID>91730330</fitemGID>
<fItemmugid>ZEY</fItemmugid>
<Quantity>2</Quantity>
<fcolorcode>TAM-K</fcolorcode>
<fsizecode>39</fsizecode>
<PRICE>39,5</PRICE>
</ESFILineItem>

<ESFILineItem>
<LineType>6</LineType>
<fitemGID>91730330</fitemGID>
<fItemmugid>ZEY</fItemmugid>
<Quantity>1</Quantity>
<fcolorcode>BL-K</fcolorcode>
<fsizecode>36</fsizecode>
<PRICE>35,3</PRICE>
</ESFILineItem>

</TradeDocumentDS>
```

ΟΙ header που χρησιμοποιώ είναι :

Authorization:Bearer 77d470b7-c961-4b9b-9364-94cc80b4c46e
Content-Type:application/xml

http://80.106.197.241:11880/eswebapi/api/rpc/FIImportDocument/

**Comment by Softweb-Adaptive-IT-Solutions** [comment]
Ευχαριστώ για την απάντηση. Απευθύνθηκα στο support και μου έδωσαν όλα όσο χρειαζόμουν. Έχω ένα πρόβλημα το call όμως.

Αυτό είναι το xml που σχημάτισα. Λειτουργεί αν το βάλω σαν αρχείο απευθείας στο server, κάνει εισαγωγή κανονικά.

```
<?xml version='1.0' encoding='UTF-8'?>
<TradeDocumentDS>

<ESFIDocumentTrade>
<version>1</version>
<fADDocumentTypeGID>ΠΑΡ</fADDocumentTypeGID>
<fADDocumentSeriesGID>ΚΕΝ-Α</fADDocumentSeriesGID>
<AdStringfield1>INTERNET</AdStringfield1>
<fTradeAccountGID>ce0052bb-cd7b-4918-a900-8b5cb04528c7</fTradeAccountGID>
<fdeliverysiteGID>1</fdeliverysiteGID></ESFIDocumentTrade>

<ESFILineItem>
<LineType>6</LineType>
<fitemGID>91730330</fitemGID>
<fItemmugid>ZEY</fItemmugid>
<Quantity>2</Quantity>
<fcolorcode>TAM-K</fcolorcode>
<fsizecode>39</fsizecode>
<PRICE>39,5</PRICE>
</ESFILineItem>

<ESFILineItem>
<LineType>6</LineType>
<fitemGID>91730330</fitemGID>
<fItemmugid>ZEY</fItemmugid>
<Quantity>1</Quantity>
<fcolorcode>BL-K</fcolorcode>
<fsizecode>36</fsizecode>
<PRICE>35,3</PRICE>
</ESFILineItem>

</TradeDocumentDS>
```

ΟΙ header που χρησιμοποιώ είναι :

Authorization:Bearer 77d470b7-c961-4b9b-9364-94cc80b4c46e
Content-Type:application/xml

To url:
/eswebapi/api/rpc/FIImportDocument/

Η απαντηση  που έρχετε είναι:
bb3b896a-37d0-41df-a576-e7b260fada76

**Comment by entersoftsa** [comment]
Δεν αναφέρετε το πρόβλημα

**Comment by Softweb-Adaptive-IT-Solutions** [comment]
Το πρόβλημα είναι ότι απαντάει το με 200, δεν βλέπω κάπου να εισάγεται.
Δεν θα έπρεπε κανονικά να μου βγάλει κάποιο μήνυμα λάθους ?
Μου απαντάει με ad6b431e-cfa3-4e4b-a955-f8d18402a716 αλλά δεν καταλαβαίνω τι σημαίνει.

**Comment by entersoftsa** [comment]
Δύο quick thoughts


  1.  Εφόσον απαντάει 200, ας το εμπιστευθούμε που σημαίνει ότι το παρ/κό εισήχθηκε
  2.  Το Guid που σας επιστρέφει είναι το GID του παρ/κού.

Κάντε ένα search στην ΒΔ στον πίνακα ESFIDocumentTrade where gid = ‘ad6b431e-cfa3-4e4b-a955-f8d18402a716’ ή ότι άλλο σας επέστρεψε σαν guid και δείτε τι θα σας επιστρέψει το query.

**Comment by Softweb-Adaptive-IT-Solutions** [comment]
Ευχαριστω πολύ, το δοκιμάζω και σας λέω τι μου δείχνει

**Comment by Softweb-Adaptive-IT-Solutions** [comment]
οκ λειτούργησε,
Ευχαριστώ πολύ για την βοήθεια.

**Comment by entersoftsa** [comment]
Να είσαι καλά

Please, μην ξεχάσεις να κλείσεις την υπόθεση στο github.
